### ISSUE TITLE
Python package maintenance guidelines - Initial checklist

### ISSUE THREAD

**Issue by kaedroho** [wagtail/django-permissionedforms#1]
https://github.com/wagtail/wagtail/wiki/Python-Package-Maintenance-Guidelines

# Documentation

## Readme

- [x] Must be written in Markdown and named README.md
- [x] Must be visible on PyPI and renders properly
- [x] Must have badges linking to PyPI and license
- [ ] Should have a badge linking to online code coverage results
- [x] Must link to the changelog
- [x] Must mention what versions of Python, Django and Wagtail are supported
- [x] Must include an installation guide. This could be an abridged version of what is in the docs, but it must link to the full guide in the docs if this is the case
- [x] ~~Must link to full documentation (or, for small packages, documentation included directly in the readme)~~ (small package)
- [x] Must link to the Github discussions board that should be enabled on the repo (see Support)
- [x] Must mention where to report security issues ([security@wagtail.io](mailto:security@wagtail.io))

##  Changelog

- [x] Must have a changelog named CHANGELOG.md
- [x] Should follow Keep a Changelog

## Contributing guide

- [ ] Must have a contributing guide which is named CONTRIBUTING.md

## License

- [x] Must have a permissive licence (such as BSD or MIT, but not GPL)
- [x] Should be licensed under BSD 3-clause, if possible
- [x] Must have a license file at the top of the repo

## ``setup.py`` / ``setup.cfg`` / ``pyproject.toml``

- [x] Dependency versions should be as wide as possible
- [x] Testing and documentation requirements listed in extras
- [x] Must have classifiers for Python, Django and Wagtail versions
- [x] Must have classifier for license
- [x] Must have project URLs linking to Documentation and Changelog

# Development Process

## Branching

- [x] Default branch must be called `main`

## PyPI

- [x] Package must have a PyPI page
- [x] At least two core team members must have admin access

# Automated testing

## Django unit tests

- [x] Should use Django’s built-in test framework
- [x] Must have unit test coverage of at least 85%
- [x] Should aim for unit test coverage of at least 90%
- [x] Migrations and tests must be excluded from coverage reports
- [x] Must have instructions on how to run unit tests

## Continuous Integration

- [x] Must have a Continuous Integration set up with Github Actions, Circle CI, or both
- [x] ~~Should test against Wagtail nightly and report issues to #nightly-build-failures channel~~ (upstream package)
- [x] Must be linted with flake8
- [x] Should be formatted with black and isort

## Support

- [x] Should provide support through Github Discussions

**Comment by gasman** [comment]
All done now, except:
> Should have a badge linking to online code coverage results

Code coverage reporting is set up locally. I couldn't get codecov.io to see this repo at all, and I find codecov annoying enough (right now it seems to be crashing out completely because I'm not giving it access to all my private repos) that I'm not going to persevere with it...

> Must have a contributing guide which is named CONTRIBUTING.md

I can't find any existing examples of this, and I think writing a full page for that for a small package like this is probably overkill. If there's a stock page I can copy in, or an organisation-wide one to link to, happy to reconsider.

> At least two core team members must have admin access

Have added @kaedroho pending acceptance, but the shared `torchbox` account (which multiple core team members have access to the login for) is already an owner.
